### ISSUE TITLE
Wemod doesn't open after today's wemod update

### ISSUE THREAD

**Issue by lonewolf0708** [DaBaival/wemod-pro-unlocker#5]
Just like the title says, Wemod had an update today and after the unlocker was ran, Wemod no longer opens at all. Here's the entry from the Event log on Windows:

```Faulting application name: WeMod.exe, version: 9.0.0.0, time stamp: 0x663bf4e5
Faulting module name: WeMod.exe, version: 9.0.0.0, time stamp: 0x663bf4e5
Exception code: 0x80000003
Fault offset: 0x055c1daa
Faulting process id: 0x0x5DBC
Faulting application start time: 0x0x1DAA592F05FB431
Faulting application path: %localappdata%\WeMod\app-9.0.0-beta00\WeMod.exe
Faulting module path: %localappdata%\WeMod\app-9.0.0-beta00\WeMod.exe
Report Id: 49fc6c80-f666-4af6-b506-1cc3c6281349
Faulting package full name: 
Faulting package-relative application ID: ```

EDIT: Updated paths to obfuscate username

**Comment by DaBaival** [comment]
stable version 8.20.0
Beta version take no account of
The original author bennett-sh warehouse project is DMCA Takedown.The project has been unattended since January 27, 2023.
![2024-05-14 130804](https://github.com/DaBaival/wemod-pro-unlocker/assets/148878832/c0c823ed-0660-4cae-8fc2-fa4df7539450)
![2024-05-14 130818](https://github.com/DaBaival/wemod-pro-unlocker/assets/148878832/f5cd3a4b-d203-4d7a-bd75-eab8ecaaf640)

**Comment by DaBaival** [comment]
latest stable version 8.20.0 can still be used

**Comment by lianyuxiuluo** [comment]
最新稳定版本已经更新到9.0.1了 已经不能使用了

**Comment by lonewolf0708** [comment]
Thanks for the info.
